name: api_ml_env
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - expat=2.7.3
  - libexpat=2.7.3
  - libffi=3.4.4
  - libzlib=1.3.1
  - openssl=3.0.19
  - pip=25.3
  - python=3.11.14
  - setuptools=80.9.0
  - sqlite=3.51.1
  - tk=8.6.15
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.12.1
      - catboost==1.2.8
      - click==8.3.1
      - colorama==0.4.6
      - contourpy==1.3.3
      - cycler==0.12.1
      - fastapi==0.128.0
      - fonttools==4.61.1
      - graphviz==0.21
      - h11==0.16.0
      - httptools==0.7.1
      - idna==3.11
      - jinja2==3.1.6
      - joblib==1.5.3
      - kiwisolver==1.4.9
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - narwhals==2.15.0
      - numpy==2.4.1
      - packaging==26.0
      - pandas==3.0.0
      - pillow==12.1.0
      - plotly==6.5.2
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pyparsing==3.3.2
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - python-multipart==0.0.21
      - pyyaml==6.0.3
      - scikit-learn==1.8.0
      - scipy==1.17.0
      - seaborn==0.13.2
      - six==1.17.0
      - starlette==0.50.0
      - threadpoolctl==3.6.0
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - uvicorn==0.40.0
      - watchfiles==1.1.1
      - websockets==16.0
      - xgboost==3.1.3
